services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: mayyat
      POSTGRES_USER: mayyat_user
      POSTGRES_PASSWORD: aaleya
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/migrations/custom:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mayyat_user -d mayyat"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://mayyat_user:aaleya@db:5432/mayyat
      JWT_SECRET: $0d341737ccbcabdd6de2ca46c08599e347c215345549779b22ef9e54df59fdbc
      CORS_ORIGIN: http://localhost:5173
      PORT: 4000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  postgres_data:
    driver: local
